name: inyeon_jangbu
description: "Local occasion ledger app"
publish_to: 'none'

version: 1.0.5+6

environment:
  sdk: ^3.12.2

dependencies:
  flutter:
    sdk: flutter
  cupertino_icons: ^1.0.8
  flutter_riverpod: ^2.6.1
  flutter_contacts: ^2.2.2
  intl: ^0.20.2
  shared_preferences: ^2.5.2
  uuid: ^4.5.1

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^6.0.0

flutter:
  uses-material-design: true
