import 'dart:convert';
import 'dart:io';

/// Replaces fast_paddle_ocr's bundled Chinese dictionary with PaddleOCR's
/// Korean dictionary so the native recognizer decodes Korean labels correctly.
///
/// The plugin ships a hard-coded Hanja/Chinese character table. That makes
/// Korean model outputs appear as Chinese characters even when the OCR model
/// itself is Korean. This script patches the cached package before build time.
void main(List<String> args) {
  final repoRoot = Directory.current;
  final dictSource = File(
    _join(repoRoot.path, 'assets', 'ocr_models', 'korean_dict.txt'),
  );

  if (!dictSource.existsSync()) {
    throw StateError('Missing Korean OCR dictionary: ${dictSource.path}');
  }

  final pubCacheRoot = _resolvePubCacheRoot();
  final packageDir = _findFastPaddlePackageDirectory(pubCacheRoot);
  final targetFile = File(
    _join(packageDir.path, 'android', 'src', 'main', 'jni', 'ppocrv5_dict.h'),
  );

  final entries = dictSource
      .readAsLinesSync(encoding: utf8)
      .map((line) => line.trimRight())
      .where((line) => line.trim().isNotEmpty)
      .toList(growable: false);

  final buffer = StringBuffer()
    ..writeln('// Generated from assets/ocr_models/korean_dict.txt')
    ..writeln(
      '// Do not edit this file manually; regenerate it from the build script.',
    )
    ..writeln('static const char* character_dict[] = {');

  for (final entry in entries) {
    buffer.writeln('    ${_quoteCString(entry)},');
  }

  buffer
    ..writeln('};')
    ..writeln(
      'static const int character_dict_size = sizeof(character_dict) / sizeof(const char*);',
    )
    ..writeln();

  targetFile.writeAsStringSync(buffer.toString(), encoding: utf8);
  stdout.writeln('Patched fast_paddle_ocr dictionary at ${targetFile.path}');
}

String _resolvePubCacheRoot() {
  final explicit = Platform.environment['PUB_CACHE'];
  if (explicit != null && explicit.isNotEmpty) {
    return explicit;
  }

  if (Platform.isWindows) {
    final localAppData = Platform.environment['LOCALAPPDATA'];
    if (localAppData != null && localAppData.isNotEmpty) {
      return _join(localAppData, 'Pub', 'Cache');
    }
  }

  final home = Platform.environment['HOME'];
  if (home == null || home.isEmpty) {
    throw StateError('Unable to resolve pub cache location.');
  }

  return _join(home, '.pub-cache');
}

Directory _findFastPaddlePackageDirectory(String pubCacheRoot) {
  final hostedDir = Directory(_join(pubCacheRoot, 'hosted', 'pub.dev'));
  if (!hostedDir.existsSync()) {
    throw StateError('pub.dev cache not found at ${hostedDir.path}');
  }

  final candidates = hostedDir
      .listSync()
      .whereType<Directory>()
      .where(
        (directory) =>
            directory.path.split(Platform.pathSeparator).last ==
            'fast_paddle_ocr-0.0.5',
      )
      .toList(growable: false);

  if (candidates.isEmpty) {
    throw StateError(
      'fast_paddle_ocr-0.0.5 is not installed in ${hostedDir.path}',
    );
  }

  return candidates.single;
}

String _quoteCString(String value) {
  final escaped = value
      .replaceAll('\\', r'\\')
      .replaceAll('"', r'\"')
      .replaceAll('\t', r'\t')
      .replaceAll('\r', r'\r')
      .replaceAll('\n', r'\n');
  return '"$escaped"';
}

String _join(
  String first, [
  String? second,
  String? third,
  String? fourth,
  String? fifth,
  String? sixth,
]) {
  final parts = <String>[first];
  if (second != null) parts.add(second);
  if (third != null) parts.add(third);
  if (fourth != null) parts.add(fourth);
  if (fifth != null) parts.add(fifth);
  if (sixth != null) parts.add(sixth);
  return parts.join(Platform.pathSeparator);
}
